# Generated by Django 6.1.1 on 2026-09-07 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('driver_age', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('coupe', 'Coupe'), ('minivan', 'Minivan'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('hatchback', 'Hatchback')], max_length=20)),
                ('safety_rating', models.PositiveIntegerField()),
                ('regional_risk_index', models.PositiveIntegerField()),
                ('driving_experience_years', models.PositiveIntegerField()),
                ('calculated_risk_score', models.PositiveIntegerField(blank=True, null=True)),
                ('initial_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='flagged', max_length=20)),
                ('deductible_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_override_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('underwriter_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision_timestamp', models.DateTimeField(blank=True, null=True)),
                ('underwriter_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Application',
                'ordering': ['-created_at'],
            },
        ),
    ]
